# Mechanics{#mechanics}

## Introduction

Combat mechanics are at the core of the warrior class, and deeply impact our talent and gearing choices and combat rotation. Therefore, it is important to build a solid foundational understanding of these mechanics in order to make the correct decisions and *understand* the theory behind our choices moving forward.

## Miss Chance

Blizzard has confirmed that players have an 8% chance to miss a creature that is 3 levels above them [@blizz_atktbl2019]. Empirical work from [@magey_atktbl2019] further corroborates a formula originally proposed by Beaza during vanilla [@beaza_miss2006], which can be summarized as:

1. If the target is mob and the difference between it's defense rating and the attacker's weapon skill is 11 or more:
$$P\left(Miss\right)\ =\ 0.05\ +\ \left(\left(T_{lvl}\cdot5\right)-Atk_{skill}\right)\cdot0.2$$
2. If the target is mob and the difference between it's defense rating and the attacker's weapon skill is 10 or less:
$$P\left(Miss\right)\ =\ 0.05\ +\ \left(\left(T_{lvl}\cdot5\right)-Atk_{skill}\right)\cdot0.1$$



## Glancing Blows

## Weapon Skill

## The Crit Cap

## Flurry