--- 
title: "Marrow's Compendium of Dragonslaying"
author: "Marrow <Nexus>"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
description: "This is a Fury Warrior Guide for World of Warcraft Classic."
---

# Preamble


This is a guide on how to be an  Fury Warrior in World of Warcraft Classic. It is a work in progress and a living document. All of the information contained within reflects what is best understood as of *today*, and some of is subject to change as more about the game is discovered.

More importantly, this is a guide for players who want to push the envelope of their class, and be the best they can be. That is not the playstyle of every player, nor am I advocating it should be. Ultimately, you should pick your race and your spec so that they're both what you *enjoy* the most. To some people that is exactly what they'll find in this guide: doing all you can do to maximize your DPS and compete with your friends, or to clear the content as fast and efficiently as possible. To some other people, it might mean playing a Night Elf and raiding as Arms - and that's completely fine. Ultimately, both groups of players will find a guild and a community that fits them and enjoy this amazing game we love so much together.
